name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch:
  pull_request_target:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js for cypress/typescript
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: pushd tests/cypress; npm install

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          continue_on_error: false
          eslint: true
          eslint_dir: tests/cypress
          eslint_extensions: ts
          eslint_auto_fix: false

