name: Prettier Check

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - 'tests/**/*.ts'
      - 'tests/**/*.js'
      - 'tests/**/*.json'
      - 'tests/**/*.yml'
      - 'tests/**/*.yaml'
      - 'tests/**/*.md'
      - 'tests/package.json'
      - 'tests/.prettierrc.json'
      - 'tests/.prettierignore'
      - '.github/workflows/prettier.yaml'

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: current

      - name: Install dependencies
        working-directory: tests
        run: npm install

      - name: Run ESLint
        working-directory: tests
        run: npm run lint

      - name: Run Prettier
        working-directory: tests
        run: npm run prettier
